[workspace]
resolver = "2"
members = ["woml-engine", "woml-native"]
default-members = ["woml-engine", "woml-native"]

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
overflow-checks = false
debug = false
incremental = false

[profile.dev]
opt-level = 0
debug = true
