// Generated by WOML Module System MS2. Do not edit.
export interface WomlImportedServices {
  readonly "spreadsheet": Readonly<{
    readonly "read": (...args: readonly unknown[]) => unknown | Promise<unknown>;
    readonly "removeEmptyRows": (...args: readonly unknown[]) => unknown | Promise<unknown>;
  }>;
}

declare const services: WomlImportedServices;
