export interface WomlEditorModuleDeclaration {
  readonly name: string;
  readonly exports: readonly string[];
}

function quoted(value: string): string {
  return JSON.stringify(value);
}

export function generateWomlEditorDeclarations(
  modules: readonly WomlEditorModuleDeclaration[]
): string {
  const merged = new Map<string, Set<string>>();
  for (const module of modules) {
    const exported = merged.get(module.name) ?? new Set<string>();
    for (const name of module.exports) exported.add(name);
    merged.set(module.name, exported);
  }
  const importedServices = [...merged.entries()]
    .sort(([left], [right]) => left.localeCompare(right))
    .flatMap(([name, exports]) => [
      `    readonly ${quoted(name)}: Readonly<{`,
      ...[...exports]
        .sort()
        .map(
          exported =>
            `      readonly ${quoted(exported)}: (...args: readonly any[]) => any;`
        ),
      '    }>;',
    ]);

  return `// Generated by WOML. Run \`woml types\` to refresh this file.
// Local modules receive services only. Pass context, attempt, and individual
// secret values explicitly from the calling WOML step.

type WomlJsonPrimitive = string | number | boolean | null;
type WomlJsonValue =
  | WomlJsonPrimitive
  | { readonly [key: string]: WomlJsonValue }
  | readonly WomlJsonValue[];

interface WomlOperationOptions {
  readonly name: string;
}

interface WomlWorkflowCallOptions {
  readonly name?: string;
  readonly timeout?: number | string;
}

interface WomlWorkflowStartOptions {
  readonly name?: string;
}

interface WomlWorkflowStartResult {
  readonly workflowId: string;
  readonly runId: string;
  readonly duplicate: boolean;
}

interface WomlTelegramSendRequest {
  readonly botToken: string;
  readonly conversationId: string;
  readonly text: string;
  readonly replyToMessageId?: string;
}

interface WomlTelegramSendResult {
  readonly provider: 'telegram';
  readonly conversationId: string;
  readonly messageId: string;
  readonly acceptedAt: string;
  readonly threadId?: string;
}

interface WomlHttpRequest {
  readonly url: string;
  readonly method?: string;
  readonly headers?: Readonly<Record<string, string>>;
  readonly query?: Readonly<Record<string, WomlJsonPrimitive>>;
  readonly json?: WomlJsonValue;
  readonly text?: string;
  readonly bytesBase64?: string;
  readonly responseType?: 'json' | 'text' | 'bytes' | 'storage';
  readonly timeout?: number | string;
  readonly timeoutMs?: number;
  readonly acceptedStatus?: { readonly minimum: number; readonly maximum: number };
  readonly redirect?: 'follow' | 'error' | 'manual';
  readonly maximumRedirects?: number;
  readonly storage?: Readonly<Record<string, WomlJsonValue>>;
  readonly idempotency?: Readonly<Record<string, WomlJsonValue>>;
}

interface WomlHttpResponse<T = WomlJsonValue> {
  readonly status: number;
  readonly ok: boolean;
  readonly headers: Readonly<Record<string, string>>;
  readonly data: T;
  readonly url: string;
  readonly redirected: boolean;
}

interface WomlDatabaseRequest {
  readonly text: string;
  readonly values?: readonly WomlJsonValue[];
}

interface WomlDatabaseResult {
  readonly rows: readonly Readonly<Record<string, WomlJsonValue>>[];
  readonly rowsAffected: number;
  readonly lastInsertId?: string | number;
}

interface WomlDatabase {
  readonly query: (input: WomlDatabaseRequest, options?: WomlOperationOptions) => Promise<WomlDatabaseResult>;
  readonly execute: (input: WomlDatabaseRequest, options?: WomlOperationOptions) => Promise<WomlDatabaseResult>;
  readonly read: (input: WomlJsonValue, options?: WomlOperationOptions) => Promise<WomlJsonValue>;
  readonly insert: (input: WomlJsonValue, options?: WomlOperationOptions) => Promise<WomlJsonValue>;
  readonly update: (input: WomlJsonValue, options?: WomlOperationOptions) => Promise<WomlJsonValue>;
  readonly delete: (input: WomlJsonValue, options?: WomlOperationOptions) => Promise<WomlJsonValue>;
  readonly transaction: (input: WomlJsonValue, options?: WomlOperationOptions) => Promise<WomlJsonValue>;
}

interface WomlStorageService {
  readonly put: (input: WomlJsonValue, options?: WomlOperationOptions) => Promise<any>;
  readonly get: (input: WomlJsonValue, options?: WomlOperationOptions) => Promise<any>;
  readonly head: (input: WomlJsonValue, options?: WomlOperationOptions) => Promise<any>;
  readonly list: (input?: WomlJsonValue, options?: WomlOperationOptions) => Promise<any>;
  readonly delete: (input: WomlJsonValue, options?: WomlOperationOptions) => Promise<any>;
}

interface WomlCacheService {
  readonly get: (key: string, options?: WomlOperationOptions) => Promise<any>;
  readonly set: (key: string, value: WomlJsonValue, options?: Readonly<Record<string, any>>) => Promise<any>;
  readonly delete: (key: string, options?: WomlOperationOptions) => Promise<any>;
  readonly has: (key: string, options?: WomlOperationOptions) => Promise<any>;
  readonly increment: (key: string, amount?: number, options?: Readonly<Record<string, any>>) => Promise<any>;
  readonly setIfAbsent: (key: string, value: WomlJsonValue, options?: Readonly<Record<string, any>>) => Promise<any>;
}

interface WomlStateEntry<T = WomlJsonValue> {
  readonly found: true;
  readonly value: T;
  readonly version: number;
  readonly updatedAt: string;
}

interface WomlMissingStateEntry {
  readonly found: false;
}

interface WomlStateMutationOptions {
  readonly name: string;
  readonly ifVersion?: number;
}

interface WomlStateService {
  readonly get: <T = WomlJsonValue>(key: string) => Promise<WomlStateEntry<T> | WomlMissingStateEntry>;
  readonly has: (key: string) => Promise<{ readonly present: boolean; readonly version?: number }>;
  readonly set: (key: string, value: WomlJsonValue, options: WomlStateMutationOptions) => Promise<{ readonly stored: true; readonly version: number; readonly updatedAt: string }>;
  readonly delete: (key: string, options: WomlStateMutationOptions) => Promise<{ readonly deleted: boolean }>;
  readonly increment: (key: string, amount: number, options: WomlStateMutationOptions) => Promise<{ readonly value: number; readonly version: number; readonly updatedAt: string }>;
  readonly setIfAbsent: (key: string, value: WomlJsonValue, options: Readonly<{ readonly name: string }>) => Promise<{ readonly stored: boolean; readonly value: WomlJsonValue; readonly version: number; readonly updatedAt: string }>;
}

interface WomlBuiltinServices {
  readonly http: {
    readonly request: <T = WomlJsonValue>(input: WomlHttpRequest, options?: WomlOperationOptions) => Promise<WomlHttpResponse<T>>;
  };
  readonly db: (config: {
    readonly driver: 'sqlite' | 'postgres';
    readonly connection: string;
  }) => WomlDatabase;
  readonly storage: WomlStorageService;
  readonly cache: WomlCacheService;
  readonly state: WomlStateService;
  readonly events: {
    readonly emit: (name: string, payload: WomlJsonValue, options?: WomlOperationOptions) => Promise<any>;
  };
  readonly workflows: {
    readonly call: <T = WomlJsonValue>(
      workflowId: string,
      payload: Readonly<Record<string, WomlJsonValue>>,
      options?: WomlWorkflowCallOptions
    ) => Promise<T>;
    readonly start: (
      workflowId: string,
      payload: Readonly<Record<string, WomlJsonValue>>,
      options?: WomlWorkflowStartOptions
    ) => Promise<WomlWorkflowStartResult>;
  };
  readonly telegram: {
    readonly send: (
      input: WomlTelegramSendRequest,
      options?: Readonly<{ readonly name?: string }>
    ) => Promise<WomlTelegramSendResult>;
  };
}

interface WomlImportedServices {
${importedServices.join('\n')}
}

declare const services: Readonly<WomlBuiltinServices & WomlImportedServices>;
`;
}

export function generateWomlLifecycleEditorDeclarations(): string {
  return `// WOML Lifecycle Runtime Binding v1. Available only inside <lifecycle> scripts.
type WomlLifecycleEvent =
  | 'run_start'
  | 'step_start'
  | 'step_success'
  | 'step_failure'
  | 'step_complete'
  | 'run_success'
  | 'run_failure'
  | 'run_cancel'
  | 'run_complete';

interface WomlLifecycleBinding {
  readonly event: WomlLifecycleEvent;
  readonly workflow: Readonly<{
    id: string;
    outcome?: 'succeeded' | 'failed' | 'cancelled';
  }>;
  readonly step?: Readonly<{
    id: string;
    outcome?: 'succeeded' | 'failed' | 'cancelled';
    attempts: number;
  }>;
  readonly failure?: Readonly<{
    code: string;
    message: string;
  }>;
}

declare const lifecycle: Readonly<WomlLifecycleBinding>;
`;
}
